INFO 2021-05-27 14:24:27,207 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-27 14:24:36,734 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 14:24:36,771 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 14:24:36,775 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 16:10:56,574 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-27 16:11:31,398 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 16:11:31,429 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 16:11:31,429 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 16:12:02,092 basehttp 154 "OPTIONS /users/login/ HTTP/1.1" 200 0
WARNING 2021-05-27 16:12:02,103 log 228 Bad Request: /users/login/
WARNING 2021-05-27 16:12:02,103 basehttp 154 "POST /users/login/ HTTP/1.1" 400 68
WARNING 2021-05-27 16:12:20,191 log 228 Bad Request: /users/login/
WARNING 2021-05-27 16:12:20,192 basehttp 154 "POST /users/login/ HTTP/1.1" 400 68
WARNING 2021-05-27 16:12:23,142 log 228 Bad Request: /users/login/
WARNING 2021-05-27 16:12:23,143 basehttp 154 "POST /users/login/ HTTP/1.1" 400 68
INFO 2021-05-27 16:12:47,048 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 16:12:47,050 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 16:12:47,059 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
WARNING 2021-05-27 16:12:55,567 log 228 Bad Request: /users/login/
WARNING 2021-05-27 16:12:55,567 basehttp 154 "POST /users/login/ HTTP/1.1" 400 68
INFO 2021-05-27 16:13:07,818 autoreload 217 E:\luffy\luffyapi\luffyapi\settings\dev.py changed, reloading.
INFO 2021-05-27 16:13:09,251 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-27 16:13:09,888 basehttp 154 "POST /users/login/ HTTP/1.1" 200 197
INFO 2021-05-27 16:13:09,928 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 16:13:09,929 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 16:13:09,933 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 16:13:18,681 basehttp 154 "POST /users/login/ HTTP/1.1" 200 197
INFO 2021-05-27 16:13:18,714 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 16:13:18,715 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 16:13:18,719 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 16:21:25,600 autoreload 217 E:\luffy\luffyapi\luffyapi\settings\dev.py changed, reloading.
INFO 2021-05-27 16:21:27,274 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-27 16:26:57,237 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 16:26:57,242 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 16:26:57,244 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 16:27:08,846 basehttp 154 "POST /users/login/ HTTP/1.1" 200 197
INFO 2021-05-27 16:27:08,882 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 16:27:08,890 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 16:27:08,893 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 16:27:36,051 basehttp 154 "POST /users/login/ HTTP/1.1" 200 197
INFO 2021-05-27 16:27:36,077 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 16:27:36,081 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 16:27:36,085 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 16:29:58,257 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 16:29:59,401 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 16:29:59,416 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 16:29:59,417 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 16:30:21,084 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 16:36:10,934 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 16:36:20,351 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 16:36:20,361 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 16:36:20,365 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 16:36:28,495 basehttp 154 "POST /users/login/ HTTP/1.1" 200 197
INFO 2021-05-27 16:36:28,519 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 16:36:28,519 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 16:36:28,528 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 16:37:53,349 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 16:37:58,313 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 16:37:58,329 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 16:37:58,330 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 16:38:01,093 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 16:38:01,198 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 16:38:01,199 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 16:38:47,078 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 16:38:57,741 basehttp 154 "POST /users/login/ HTTP/1.1" 200 197
INFO 2021-05-27 16:38:57,771 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 16:38:57,774 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 16:38:57,775 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 16:41:52,293 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 16:41:56,219 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 16:41:56,219 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 16:41:56,219 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 16:42:44,470 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 16:42:53,700 basehttp 154 "POST /users/login/ HTTP/1.1" 200 197
INFO 2021-05-27 16:42:53,732 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 16:42:53,733 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 16:42:53,734 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 16:43:08,781 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 16:44:12,089 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 16:44:16,121 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 16:44:16,136 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 16:44:16,136 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 16:46:38,459 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 16:48:41,702 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 16:49:21,461 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 16:49:35,160 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 16:49:35,205 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 16:49:35,219 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 16:49:42,909 basehttp 154 "OPTIONS /users/login/ HTTP/1.1" 200 0
INFO 2021-05-27 16:49:43,004 basehttp 154 "POST /users/login/ HTTP/1.1" 200 197
INFO 2021-05-27 16:49:43,041 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 16:49:43,042 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 16:49:43,053 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 16:53:17,258 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 16:53:51,133 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 17:01:28,136 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 17:01:28,157 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 17:01:28,168 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 17:01:38,077 basehttp 154 "OPTIONS /users/login/ HTTP/1.1" 200 0
INFO 2021-05-27 17:01:38,163 basehttp 154 "POST /users/login/ HTTP/1.1" 200 197
INFO 2021-05-27 17:01:38,185 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 17:01:38,201 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 17:01:38,201 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 17:02:10,916 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 17:02:10,918 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 17:02:10,918 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 17:03:57,919 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 17:03:57,996 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 17:03:57,996 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 17:04:38,461 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 17:04:41,915 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 17:04:41,967 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 17:04:41,978 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 17:05:02,445 basehttp 154 "POST /users/login/ HTTP/1.1" 200 197
INFO 2021-05-27 17:05:02,472 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 17:05:02,474 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 17:05:02,475 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 17:07:19,006 basehttp 154 "POST /users/login/ HTTP/1.1" 200 197
INFO 2021-05-27 17:07:19,039 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 17:07:19,039 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 17:07:19,041 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 17:07:24,026 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 17:07:24,026 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 17:07:24,027 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 17:07:33,172 basehttp 154 "POST /users/login/ HTTP/1.1" 200 197
INFO 2021-05-27 17:07:33,193 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 17:07:33,199 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 17:07:33,204 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 17:15:22,204 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 17:15:22,226 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 17:15:22,226 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 17:15:32,453 basehttp 154 "POST /users/login/ HTTP/1.1" 200 197
INFO 2021-05-27 17:15:32,490 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 17:15:32,490 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 17:15:32,491 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 17:15:43,151 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 17:15:43,155 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 17:15:43,158 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 17:15:58,036 basehttp 154 "POST /users/login/ HTTP/1.1" 200 197
INFO 2021-05-27 17:15:58,065 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 17:15:58,071 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 17:15:58,072 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
WARNING 2021-05-27 17:17:34,688 log 228 Bad Request: /users/login/
WARNING 2021-05-27 17:17:34,689 basehttp 154 "POST /users/login/ HTTP/1.1" 400 68
WARNING 2021-05-27 17:18:20,058 log 228 Bad Request: /users/login/
WARNING 2021-05-27 17:18:20,059 basehttp 154 "POST /users/login/ HTTP/1.1" 400 68
INFO 2021-05-27 17:18:27,326 basehttp 154 "POST /users/login/ HTTP/1.1" 200 197
INFO 2021-05-27 17:18:27,369 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 17:18:27,372 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 17:18:27,385 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
WARNING 2021-05-27 17:18:52,802 log 228 Bad Request: /users/login/
WARNING 2021-05-27 17:18:52,803 basehttp 154 "POST /users/login/ HTTP/1.1" 400 68
INFO 2021-05-27 17:19:02,043 basehttp 154 "POST /users/login/ HTTP/1.1" 200 197
INFO 2021-05-27 17:19:02,068 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 17:19:02,070 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 17:19:02,073 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
WARNING 2021-05-27 17:28:43,293 log 228 Bad Request: /users/login/
WARNING 2021-05-27 17:28:43,294 basehttp 154 "POST /users/login/ HTTP/1.1" 400 68
INFO 2021-05-27 17:28:48,033 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 17:28:48,036 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-27 17:28:48,036 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 20:30:35,810 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-05-27 20:30:38,119 log 228 Not Found: /
WARNING 2021-05-27 20:30:38,120 basehttp 154 "GET / HTTP/1.1" 404 2372
WARNING 2021-05-27 20:30:38,315 log 228 Not Found: /favicon.ico
WARNING 2021-05-27 20:30:38,315 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2423
WARNING 2021-05-27 20:30:48,541 log 228 Not Found: /getcaptcha
WARNING 2021-05-27 20:30:48,542 basehttp 154 "GET /getcaptcha HTTP/1.1" 404 2420
INFO 2021-05-27 20:31:15,534 basehttp 154 "GET /users/getcaptcha HTTP/1.1" 301 0
ERROR 2021-05-27 20:31:15,690 log 228 Internal Server Error: /users/getcaptcha/
Traceback (most recent call last):
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: __init__() takes 1 positional argument but 2 were given
ERROR 2021-05-27 20:31:15,691 basehttp 154 "GET /users/getcaptcha/ HTTP/1.1" 500 69108
INFO 2021-05-27 20:34:45,737 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\views.py changed, reloading.
INFO 2021-05-27 20:34:48,150 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-27 20:38:08,860 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-05-27 20:38:10,965 log 228 Not Found: /
WARNING 2021-05-27 20:38:10,965 basehttp 154 "GET / HTTP/1.1" 404 2372
ERROR 2021-05-27 20:38:52,750 log 228 Internal Server Error: /users/getcaptcha/
Traceback (most recent call last):
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: __init__() takes 1 positional argument but 2 were given
ERROR 2021-05-27 20:38:52,751 basehttp 154 "GET /users/getcaptcha/ HTTP/1.1" 500 69108
INFO 2021-05-27 20:48:42,010 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\views.py changed, reloading.
INFO 2021-05-27 20:48:43,481 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-27 20:49:54,894 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\views.py changed, reloading.
INFO 2021-05-27 20:49:56,595 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-27 20:50:39,832 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\urls.py changed, reloading.
INFO 2021-05-27 20:50:41,355 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-27 20:57:22,561 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-27 20:57:42,695 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-27 20:57:42,763 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-27 20:57:42,763 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-28 08:06:32,696 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-28 08:06:53,815 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-28 08:06:53,864 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-28 08:06:53,874 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-28 08:06:53,876 basehttp 154 "GET /media/banner/banner1.png HTTP/1.1" 304 0
INFO 2021-05-28 08:06:53,876 basehttp 154 "GET /media/banner/banner2.png HTTP/1.1" 304 0
INFO 2021-05-28 08:07:00,956 basehttp 154 "OPTIONS /users/login/ HTTP/1.1" 200 0
WARNING 2021-05-28 08:07:00,972 log 228 Bad Request: /users/login/
WARNING 2021-05-28 08:07:00,973 basehttp 154 "POST /users/login/ HTTP/1.1" 400 68
WARNING 2021-05-28 08:07:04,970 log 228 Bad Request: /users/login/
WARNING 2021-05-28 08:07:04,970 basehttp 154 "POST /users/login/ HTTP/1.1" 400 68
WARNING 2021-05-28 08:07:55,731 log 228 Bad Request: /users/login/
WARNING 2021-05-28 08:07:55,732 basehttp 154 "POST /users/login/ HTTP/1.1" 400 68
WARNING 2021-05-28 08:08:15,746 log 228 Bad Request: /users/login/
WARNING 2021-05-28 08:08:15,746 basehttp 154 "POST /users/login/ HTTP/1.1" 400 68
INFO 2021-05-28 08:08:28,365 basehttp 154 "POST /users/login/ HTTP/1.1" 200 197
INFO 2021-05-28 08:08:28,402 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-28 08:08:28,422 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-28 08:08:28,423 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-28 08:08:55,203 basehttp 154 "POST /users/login/ HTTP/1.1" 200 197
INFO 2021-05-28 08:08:55,229 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-28 08:08:55,230 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-28 08:08:55,230 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-28 08:10:44,737 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-28 08:10:44,749 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-28 08:10:44,750 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-28 08:36:02,861 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-05-28 08:36:09,582 log 228 Not Found: /pc-geetest/register
WARNING 2021-05-28 08:36:09,583 basehttp 154 "GET /pc-geetest/register?t=1622162169549 HTTP/1.1" 404 2463
WARNING 2021-05-28 08:37:35,366 log 228 Not Found: /pc-geetest/register
WARNING 2021-05-28 08:37:35,367 basehttp 154 "GET /pc-geetest/register?t=1622162255349 HTTP/1.1" 404 2463
WARNING 2021-05-28 08:38:39,230 log 228 Not Found: /pc-geetest/register
WARNING 2021-05-28 08:38:39,231 basehttp 154 "GET /pc-geetest/register?t=1622162319222 HTTP/1.1" 404 2463
WARNING 2021-05-28 08:39:12,483 log 228 Not Found: /
WARNING 2021-05-28 08:39:12,484 basehttp 154 "GET / HTTP/1.1" 404 2372
WARNING 2021-05-28 08:39:12,610 log 228 Not Found: /favicon.ico
WARNING 2021-05-28 08:39:12,611 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2423
WARNING 2021-05-28 08:39:24,492 log 228 Not Found: /users/
WARNING 2021-05-28 08:39:24,492 basehttp 154 "GET /users/ HTTP/1.1" 404 2810
ERROR 2021-05-28 08:39:31,984 log 228 Internal Server Error: /users/pc-geetest/register
Traceback (most recent call last):
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\envs\luffy\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\envs\luffy\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\envs\luffy\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\luffy\luffyapi\luffyapi\apps\users\views.py", line 22, in get
    request.session[gt.GT_STATUS_SESSIONKEY] = status
AttributeError: 'GeetestLib' object has no attribute 'GT_STATUS_SESSIONKEY'
ERROR 2021-05-28 08:39:31,986 basehttp 154 "GET /users/pc-geetest/register HTTP/1.1" 500 99430
INFO 2021-05-28 10:32:24,901 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-05-28 10:32:28,470 log 228 Not Found: /pc-geetest/register
WARNING 2021-05-28 10:32:28,471 basehttp 154 "GET /pc-geetest/register?t=1622169148446 HTTP/1.1" 404 2463
WARNING 2021-05-28 10:32:40,400 log 228 Not Found: /
WARNING 2021-05-28 10:32:40,401 basehttp 154 "GET / HTTP/1.1" 404 2372
WARNING 2021-05-28 10:32:44,279 log 228 Not Found: /users
WARNING 2021-05-28 10:32:44,280 basehttp 154 "GET /users HTTP/1.1" 404 2405
WARNING 2021-05-28 10:32:48,080 log 228 Not Found: /users/
WARNING 2021-05-28 10:32:48,081 basehttp 154 "GET /users/ HTTP/1.1" 404 2810
INFO 2021-05-28 10:32:54,723 basehttp 154 "GET /users/pc-geetest/register HTTP/1.1" 200 105
INFO 2021-05-28 10:42:57,765 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-05-28 10:42:58,310 log 228 Not Found: /users/
WARNING 2021-05-28 10:42:58,311 basehttp 154 "GET /users/ HTTP/1.1" 404 2810
INFO 2021-05-28 10:43:05,563 basehttp 154 "GET /users/pc-geetest/ajax_validate HTTP/1.1" 200 105
WARNING 2021-05-28 10:43:39,323 log 228 Not Found: /users/
WARNING 2021-05-28 10:43:39,324 basehttp 154 "GET /users/ HTTP/1.1" 404 2810
INFO 2021-05-28 10:43:45,535 basehttp 154 "GET /users/pc-geetest/register HTTP/1.1" 200 105
INFO 2021-05-28 11:01:15,457 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-28 11:01:19,011 basehttp 154 "GET /users/pc-geetest/register HTTP/1.1" 200 105
INFO 2021-05-28 11:01:21,544 basehttp 154 "GET /users/pc-geetest/register HTTP/1.1" 200 105
INFO 2021-05-28 11:01:23,828 basehttp 154 "GET /users/pc-geetest/register HTTP/1.1" 200 105
INFO 2021-05-28 11:01:26,307 basehttp 154 "GET /users/pc-geetest/register HTTP/1.1" 200 105
INFO 2021-05-28 11:01:32,112 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\views.py changed, reloading.
INFO 2021-05-28 11:01:33,603 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-28 11:01:36,778 basehttp 154 "GET /users/pc-geetest/register HTTP/1.1" 200 105
INFO 2021-05-28 11:01:45,684 basehttp 154 "GET /users/pc-geetest/register HTTP/1.1" 200 105
INFO 2021-05-28 11:01:46,759 basehttp 154 "GET /users/pc-geetest/register HTTP/1.1" 200 105
INFO 2021-05-28 11:05:12,698 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\views.py changed, reloading.
INFO 2021-05-28 11:05:14,200 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-28 11:22:49,897 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\urls.py changed, reloading.
INFO 2021-05-28 11:22:51,680 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-28 11:28:38,214 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-28 11:28:38,215 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-28 11:28:38,216 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-28 11:28:40,211 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 11:28:42,095 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 11:29:53,845 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 11:30:07,675 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 11:31:02,782 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 11:34:30,140 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-28 11:34:30,161 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-28 11:34:30,161 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-28 11:34:32,175 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 14:01:16,342 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-28 14:01:39,532 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-28 14:01:39,585 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-28 14:01:39,586 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-28 14:01:46,647 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 14:02:01,849 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 14:02:15,576 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 14:03:15,601 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 14:03:57,917 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 14:04:08,099 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 14:10:51,321 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 14:11:03,139 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 14:11:13,044 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 14:28:32,778 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 14:36:15,104 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 14:38:56,888 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 14:39:07,503 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 14:39:25,169 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 14:40:15,899 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 14:40:22,572 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 14:40:24,908 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-28 14:40:24,908 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-28 14:40:24,911 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-28 14:40:40,153 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 14:40:41,987 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 14:40:48,636 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 14:40:54,583 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-28 14:40:54,586 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-28 14:40:54,587 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-28 14:43:16,330 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 14:43:21,991 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 14:43:26,092 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-28 14:43:26,094 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-28 14:43:26,095 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-28 14:44:37,783 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 14:57:33,915 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 14:57:35,112 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 14:58:11,733 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 14:58:26,052 basehttp 154 "OPTIONS /users/login/ HTTP/1.1" 200 0
INFO 2021-05-28 14:58:26,197 basehttp 154 "POST /users/login/ HTTP/1.1" 200 197
INFO 2021-05-28 14:58:26,235 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-28 14:58:26,269 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-28 14:58:26,278 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-28 14:58:36,673 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
WARNING 2021-05-28 14:58:38,715 log 228 Bad Request: /users/login/
WARNING 2021-05-28 14:58:38,715 basehttp 154 "POST /users/login/ HTTP/1.1" 400 89
INFO 2021-05-28 15:01:05,159 basehttp 154 "POST /users/login/ HTTP/1.1" 200 197
INFO 2021-05-28 15:01:05,192 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-28 15:01:05,197 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-28 15:01:05,197 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-28 15:01:10,226 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 15:01:12,140 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 15:01:17,156 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 15:01:30,546 basehttp 154 "POST /users/login/ HTTP/1.1" 200 197
INFO 2021-05-28 15:01:30,624 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-28 15:01:30,625 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-28 15:01:30,632 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-28 15:01:32,475 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 15:11:07,998 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 15:11:16,637 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 16:18:44,154 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\views.py changed, reloading.
INFO 2021-05-28 16:18:46,400 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-28 16:20:29,914 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\views.py changed, reloading.
INFO 2021-05-28 16:20:31,360 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-28 16:26:19,957 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\views.py changed, reloading.
INFO 2021-05-28 16:26:21,720 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-28 16:27:16,154 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\urls.py changed, reloading.
INFO 2021-05-28 16:27:17,640 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-28 16:28:31,689 autoreload 217 E:\luffy\luffyapi\luffyapi\settings\dev.py changed, reloading.
INFO 2021-05-28 16:28:33,209 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-28 16:28:55,957 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\urls.py changed, reloading.
INFO 2021-05-28 16:28:57,398 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-28 16:29:32,998 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-28 16:29:33,080 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-28 16:29:33,081 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-28 16:30:32,535 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 16:30:38,789 basehttp 154 "OPTIONS /users/capycha HTTP/1.1" 200 0
INFO 2021-05-28 16:30:38,894 basehttp 154 "POST /users/capycha HTTP/1.1" 200 20
INFO 2021-05-28 16:33:27,317 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 16:33:33,490 basehttp 154 "POST /users/capycha HTTP/1.1" 200 20
INFO 2021-05-28 16:36:33,646 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 16:36:38,584 basehttp 154 "POST /users/capycha HTTP/1.1" 200 20
WARNING 2021-05-28 16:36:38,594 log 228 Bad Request: /users/login/
WARNING 2021-05-28 16:36:38,595 basehttp 154 "POST /users/login/ HTTP/1.1" 400 89
INFO 2021-05-28 16:36:51,392 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 16:36:56,477 basehttp 154 "POST /users/capycha HTTP/1.1" 200 20
INFO 2021-05-28 16:36:56,610 basehttp 154 "POST /users/login/ HTTP/1.1" 200 197
INFO 2021-05-28 16:36:56,683 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-28 16:36:56,706 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-28 16:36:56,710 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-28 16:37:04,582 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 16:37:09,858 basehttp 154 "POST /users/capycha HTTP/1.1" 200 20
WARNING 2021-05-28 16:37:09,863 log 228 Bad Request: /users/login/
WARNING 2021-05-28 16:37:09,864 basehttp 154 "POST /users/login/ HTTP/1.1" 400 89
INFO 2021-05-28 16:37:17,639 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 16:37:27,312 basehttp 154 "POST /users/capycha HTTP/1.1" 200 20
INFO 2021-05-28 16:37:27,420 basehttp 154 "POST /users/login/ HTTP/1.1" 200 197
INFO 2021-05-28 16:37:27,466 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-28 16:37:27,471 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-28 16:37:27,481 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-28 16:54:18,975 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 16:54:23,851 basehttp 154 "POST /users/capycha HTTP/1.1" 200 20
INFO 2021-05-28 16:54:23,856 basehttp 154 "OPTIONS /users/login HTTP/1.1" 200 0
ERROR 2021-05-28 16:54:24,032 log 228 Internal Server Error: /users/login
Traceback (most recent call last):
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\envs\luffy\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "E:\envs\luffy\lib\site-packages\django\middleware\common.py", line 53, in process_request
    path = self.get_full_path_with_slash(request)
  File "E:\envs\luffy\lib\site-packages\django\middleware\common.py", line 93, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to api.luffycity.cn:8001/users/login/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2021-05-28 16:54:24,033 basehttp 154 "POST /users/login HTTP/1.1" 500 70343
INFO 2021-05-28 16:55:24,116 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 16:55:28,522 basehttp 154 "POST /users/capycha HTTP/1.1" 200 20
WARNING 2021-05-28 16:55:28,640 log 228 Bad Request: /users/login/
WARNING 2021-05-28 16:55:28,640 basehttp 154 "POST /users/login/ HTTP/1.1" 400 68
INFO 2021-05-28 16:55:38,527 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 16:55:43,623 basehttp 154 "POST /users/capycha HTTP/1.1" 200 20
INFO 2021-05-28 16:55:43,725 basehttp 154 "POST /users/login/ HTTP/1.1" 200 197
INFO 2021-05-28 16:55:43,769 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-28 16:55:43,771 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-28 16:55:43,779 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-28 16:58:21,665 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 16:58:25,588 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 16:58:26,967 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 16:59:48,227 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 16:59:51,334 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 16:59:51,845 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 16:59:52,156 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 16:59:52,250 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 17:00:35,767 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 17:00:44,004 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 17:01:44,788 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 17:04:47,798 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 17:04:52,508 basehttp 154 "POST /users/capycha HTTP/1.1" 200 20
INFO 2021-05-28 17:04:52,513 basehttp 154 "OPTIONS /users/login/ HTTP/1.1" 200 0
WARNING 2021-05-28 17:04:52,542 log 228 Bad Request: /users/login/
WARNING 2021-05-28 17:04:52,543 basehttp 154 "POST /users/login/ HTTP/1.1" 400 68
INFO 2021-05-28 17:04:57,936 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 17:04:58,550 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 17:04:59,397 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 17:15:52,647 basehttp 154 "POST /users/capycha HTTP/1.1" 200 20
WARNING 2021-05-28 17:15:52,665 log 228 Bad Request: /users/login/
WARNING 2021-05-28 17:15:52,666 basehttp 154 "POST /users/login/ HTTP/1.1" 400 68
INFO 2021-05-28 17:15:54,245 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-28 17:17:16,935 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\views.py changed, reloading.
INFO 2021-05-28 17:17:18,877 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-28 17:18:50,139 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-28 17:18:50,176 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-28 17:18:50,180 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-30 21:00:03,540 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-30 21:00:33,470 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-30 21:00:41,899 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-30 21:00:41,927 basehttp 154 "GET /media/banner/banner1.png HTTP/1.1" 304 0
INFO 2021-05-30 21:00:41,927 basehttp 154 "GET /media/banner/banner2.png HTTP/1.1" 304 0
INFO 2021-05-30 21:00:41,941 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-30 21:00:41,942 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-30 21:01:34,693 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-30 21:01:34,694 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-30 21:01:34,701 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-30 21:01:40,219 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-30 21:01:40,221 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-30 21:01:40,222 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-30 21:09:08,462 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-30 21:09:13,915 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-30 21:09:13,930 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-30 21:09:13,931 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-30 21:09:26,095 basehttp 154 "GET /users/capycha HTTP/1.1" 200 105
INFO 2021-05-30 21:09:31,687 basehttp 154 "OPTIONS /users/capycha HTTP/1.1" 200 0
INFO 2021-05-30 21:09:31,787 basehttp 154 "POST /users/capycha HTTP/1.1" 200 20
INFO 2021-05-30 21:09:31,790 basehttp 154 "OPTIONS /users/login/ HTTP/1.1" 200 0
INFO 2021-05-30 21:09:31,900 basehttp 154 "POST /users/login/ HTTP/1.1" 200 197
INFO 2021-05-30 21:09:31,943 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-30 21:09:31,963 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-30 21:09:31,963 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-31 07:51:06,998 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-31 07:51:17,476 basehttp 154 "GET /home/nav HTTP/1.1" 301 0
INFO 2021-05-31 07:51:17,477 basehttp 154 "GET /home/btmnav HTTP/1.1" 301 0
INFO 2021-05-31 07:51:17,492 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-31 07:51:17,543 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-31 07:51:17,548 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-31 07:51:17,549 basehttp 154 "GET /media/banner/banner2.png HTTP/1.1" 200 111031
INFO 2021-05-31 07:51:17,551 basehttp 154 "GET /media/banner/banner1.png HTTP/1.1" 200 264105
INFO 2021-05-31 07:55:00,580 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\views.py changed, reloading.
INFO 2021-05-31 07:55:02,357 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-31 08:07:12,104 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\urls.py changed, reloading.
INFO 2021-05-31 08:07:13,608 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-31 08:07:16,151 basehttp 154 "GET /users/capycha HTTP/1.1" 301 0
INFO 2021-05-31 08:07:16,271 basehttp 154 "GET /users/capycha/ HTTP/1.1" 200 105
INFO 2021-05-31 08:07:33,895 basehttp 154 "GET /users/capycha/ HTTP/1.1" 200 105
INFO 2021-05-31 08:07:38,903 basehttp 154 "OPTIONS /users/capycha HTTP/1.1" 200 0
ERROR 2021-05-31 08:07:39,036 log 228 Internal Server Error: /users/capycha
Traceback (most recent call last):
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\envs\luffy\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "E:\envs\luffy\lib\site-packages\django\middleware\common.py", line 53, in process_request
    path = self.get_full_path_with_slash(request)
  File "E:\envs\luffy\lib\site-packages\django\middleware\common.py", line 93, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to api.luffycity.cn:8001/users/capycha/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2021-05-31 08:07:39,037 basehttp 154 "POST /users/capycha HTTP/1.1" 500 70376
INFO 2021-05-31 08:07:40,765 basehttp 154 "GET /users/capycha/ HTTP/1.1" 200 105
ERROR 2021-05-31 08:07:54,011 log 228 Internal Server Error: /users/capycha
Traceback (most recent call last):
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\envs\luffy\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "E:\envs\luffy\lib\site-packages\django\middleware\common.py", line 53, in process_request
    path = self.get_full_path_with_slash(request)
  File "E:\envs\luffy\lib\site-packages\django\middleware\common.py", line 93, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to api.luffycity.cn:8001/users/capycha/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2021-05-31 08:07:54,012 basehttp 154 "POST /users/capycha HTTP/1.1" 500 70376
INFO 2021-05-31 08:07:54,794 basehttp 154 "GET /users/capycha/ HTTP/1.1" 200 105
INFO 2021-05-31 08:08:04,952 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\urls.py changed, reloading.
INFO 2021-05-31 08:08:06,497 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-05-31 08:08:17,924 log 228 Not Found: /users/capycha/
WARNING 2021-05-31 08:08:17,925 basehttp 154 "GET /users/capycha/ HTTP/1.1" 404 2645
WARNING 2021-05-31 08:08:20,843 log 228 Not Found: /users/capycha/
WARNING 2021-05-31 08:08:20,843 basehttp 154 "GET /users/capycha/ HTTP/1.1" 404 2645
WARNING 2021-05-31 08:08:22,210 log 228 Not Found: /users/capycha/
WARNING 2021-05-31 08:08:22,211 basehttp 154 "GET /users/capycha/ HTTP/1.1" 404 2645
WARNING 2021-05-31 08:08:22,402 log 228 Not Found: /users/capycha/
WARNING 2021-05-31 08:08:22,402 basehttp 154 "GET /users/capycha/ HTTP/1.1" 404 2645
WARNING 2021-05-31 08:08:22,628 log 228 Not Found: /users/capycha/
WARNING 2021-05-31 08:08:22,629 basehttp 154 "GET /users/capycha/ HTTP/1.1" 404 2645
WARNING 2021-05-31 08:08:22,837 log 228 Not Found: /users/capycha/
WARNING 2021-05-31 08:08:22,837 basehttp 154 "GET /users/capycha/ HTTP/1.1" 404 2645
WARNING 2021-05-31 08:08:23,699 log 228 Not Found: /users/capycha/
WARNING 2021-05-31 08:08:23,699 basehttp 154 "GET /users/capycha/ HTTP/1.1" 404 2645
WARNING 2021-05-31 08:08:23,884 log 228 Not Found: /users/capycha/
WARNING 2021-05-31 08:08:23,884 basehttp 154 "GET /users/capycha/ HTTP/1.1" 404 2645
WARNING 2021-05-31 08:08:24,074 log 228 Not Found: /users/capycha/
WARNING 2021-05-31 08:08:24,074 basehttp 154 "GET /users/capycha/ HTTP/1.1" 404 2645
WARNING 2021-05-31 08:08:24,266 log 228 Not Found: /users/capycha/
WARNING 2021-05-31 08:08:24,266 basehttp 154 "GET /users/capycha/ HTTP/1.1" 404 2645
WARNING 2021-05-31 08:08:24,466 log 228 Not Found: /users/capycha/
WARNING 2021-05-31 08:08:24,467 basehttp 154 "GET /users/capycha/ HTTP/1.1" 404 2645
INFO 2021-05-31 08:08:43,555 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-05-31 08:08:50,763 log 228 Not Found: /users/capycha/
WARNING 2021-05-31 08:08:50,763 basehttp 154 "GET /users/capycha/ HTTP/1.1" 404 2645
WARNING 2021-05-31 08:09:03,123 log 228 Not Found: /users/capycha/
WARNING 2021-05-31 08:09:03,124 basehttp 154 "GET /users/capycha/ HTTP/1.1" 404 2645
WARNING 2021-05-31 08:09:06,245 log 228 Not Found: /users/capycha/
WARNING 2021-05-31 08:09:06,245 basehttp 154 "GET /users/capycha/ HTTP/1.1" 404 2645
WARNING 2021-05-31 08:09:06,427 log 228 Not Found: /users/capycha/
WARNING 2021-05-31 08:09:06,427 basehttp 154 "GET /users/capycha/ HTTP/1.1" 404 2645
WARNING 2021-05-31 08:09:06,660 log 228 Not Found: /users/capycha/
WARNING 2021-05-31 08:09:06,660 basehttp 154 "GET /users/capycha/ HTTP/1.1" 404 2645
WARNING 2021-05-31 08:09:06,866 log 228 Not Found: /users/capycha/
WARNING 2021-05-31 08:09:06,867 basehttp 154 "GET /users/capycha/ HTTP/1.1" 404 2645
WARNING 2021-05-31 08:09:07,066 log 228 Not Found: /users/capycha/
WARNING 2021-05-31 08:09:07,067 basehttp 154 "GET /users/capycha/ HTTP/1.1" 404 2645
WARNING 2021-05-31 08:09:07,259 log 228 Not Found: /users/capycha/
WARNING 2021-05-31 08:09:07,260 basehttp 154 "GET /users/capycha/ HTTP/1.1" 404 2645
WARNING 2021-05-31 08:09:07,443 log 228 Not Found: /users/capycha/
WARNING 2021-05-31 08:09:07,443 basehttp 154 "GET /users/capycha/ HTTP/1.1" 404 2645
WARNING 2021-05-31 08:09:07,626 log 228 Not Found: /users/capycha/
WARNING 2021-05-31 08:09:07,626 basehttp 154 "GET /users/capycha/ HTTP/1.1" 404 2645
WARNING 2021-05-31 08:09:07,819 log 228 Not Found: /users/capycha/
WARNING 2021-05-31 08:09:07,820 basehttp 154 "GET /users/capycha/ HTTP/1.1" 404 2645
INFO 2021-05-31 08:09:54,279 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\urls.py changed, reloading.
INFO 2021-05-31 08:09:55,695 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-31 08:10:03,154 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-31 08:10:03,195 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-31 08:10:03,208 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
WARNING 2021-05-31 08:10:11,707 log 228 Not Found: /users/capycha/
WARNING 2021-05-31 08:10:11,708 basehttp 154 "GET /users/capycha/ HTTP/1.1" 404 2645
WARNING 2021-05-31 08:10:13,826 log 228 Not Found: /users/capycha/
WARNING 2021-05-31 08:10:13,826 basehttp 154 "GET /users/capycha/ HTTP/1.1" 404 2645
WARNING 2021-05-31 08:10:13,994 log 228 Not Found: /users/capycha/
WARNING 2021-05-31 08:10:13,994 basehttp 154 "GET /users/capycha/ HTTP/1.1" 404 2645
INFO 2021-05-31 08:10:22,955 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\urls.py changed, reloading.
INFO 2021-05-31 08:10:24,416 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-31 08:10:28,676 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-31 08:10:28,721 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-31 08:10:28,723 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-31 08:10:41,752 basehttp 154 "GET /users/capycha/ HTTP/1.1" 200 105
INFO 2021-05-31 08:10:47,750 basehttp 154 "OPTIONS /users/capycha HTTP/1.1" 200 0
ERROR 2021-05-31 08:10:47,874 log 228 Internal Server Error: /users/capycha
Traceback (most recent call last):
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\envs\luffy\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "E:\envs\luffy\lib\site-packages\django\middleware\common.py", line 53, in process_request
    path = self.get_full_path_with_slash(request)
  File "E:\envs\luffy\lib\site-packages\django\middleware\common.py", line 93, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to api.luffycity.cn:8001/users/capycha/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2021-05-31 08:10:47,875 basehttp 154 "POST /users/capycha HTTP/1.1" 500 70376
INFO 2021-05-31 08:10:49,913 basehttp 154 "GET /users/capycha/ HTTP/1.1" 200 105
ERROR 2021-05-31 08:10:54,421 log 228 Internal Server Error: /users/capycha
Traceback (most recent call last):
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\envs\luffy\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "E:\envs\luffy\lib\site-packages\django\middleware\common.py", line 53, in process_request
    path = self.get_full_path_with_slash(request)
  File "E:\envs\luffy\lib\site-packages\django\middleware\common.py", line 93, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to api.luffycity.cn:8001/users/capycha/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2021-05-31 08:10:54,421 basehttp 154 "POST /users/capycha HTTP/1.1" 500 70376
INFO 2021-05-31 08:10:55,132 basehttp 154 "GET /users/capycha/ HTTP/1.1" 200 105
INFO 2021-05-31 08:11:05,255 basehttp 154 "GET /users/capycha/ HTTP/1.1" 200 105
ERROR 2021-05-31 08:11:12,084 log 228 Internal Server Error: /users/capycha
Traceback (most recent call last):
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\envs\luffy\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "E:\envs\luffy\lib\site-packages\django\middleware\common.py", line 53, in process_request
    path = self.get_full_path_with_slash(request)
  File "E:\envs\luffy\lib\site-packages\django\middleware\common.py", line 93, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to api.luffycity.cn:8001/users/capycha/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2021-05-31 08:11:12,085 basehttp 154 "POST /users/capycha HTTP/1.1" 500 70376
INFO 2021-05-31 08:11:15,544 basehttp 154 "GET /users/capycha/ HTTP/1.1" 200 105
INFO 2021-05-31 08:11:24,694 basehttp 154 "GET /users/capycha/ HTTP/1.1" 200 105
INFO 2021-05-31 08:16:10,408 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-31 08:16:24,424 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-31 08:16:24,472 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-31 08:16:24,473 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-31 08:16:35,746 basehttp 154 "GET /users/capycha/ HTTP/1.1" 200 105
INFO 2021-05-31 08:16:42,451 basehttp 154 "OPTIONS /users/capycha HTTP/1.1" 200 0
ERROR 2021-05-31 08:16:42,599 log 228 Internal Server Error: /users/capycha
Traceback (most recent call last):
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\envs\luffy\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "E:\envs\luffy\lib\site-packages\django\middleware\common.py", line 53, in process_request
    path = self.get_full_path_with_slash(request)
  File "E:\envs\luffy\lib\site-packages\django\middleware\common.py", line 93, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to api.luffycity.cn:8001/users/capycha/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2021-05-31 08:16:42,600 basehttp 154 "POST /users/capycha HTTP/1.1" 500 70376
INFO 2021-05-31 08:17:35,304 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-31 08:17:43,876 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-31 08:17:43,923 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-31 08:17:43,924 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
WARNING 2021-05-31 08:17:55,284 log 228 Not Found: /users/capycha/
WARNING 2021-05-31 08:17:55,284 basehttp 154 "GET /users/capycha/ HTTP/1.1" 404 2645
WARNING 2021-05-31 08:17:59,482 log 228 Not Found: /users/capycha/
WARNING 2021-05-31 08:17:59,482 basehttp 154 "GET /users/capycha/ HTTP/1.1" 404 2645
WARNING 2021-05-31 08:18:00,866 log 228 Not Found: /users/capycha/
WARNING 2021-05-31 08:18:00,867 basehttp 154 "GET /users/capycha/ HTTP/1.1" 404 2645
WARNING 2021-05-31 08:18:01,013 log 228 Not Found: /users/capycha/
WARNING 2021-05-31 08:18:01,014 basehttp 154 "GET /users/capycha/ HTTP/1.1" 404 2645
INFO 2021-05-31 08:18:37,513 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-05-31 08:18:52,074 log 228 Not Found: /users/capycha/
WARNING 2021-05-31 08:18:52,074 basehttp 154 "GET /users/capycha/ HTTP/1.1" 404 2645
INFO 2021-05-31 08:19:51,305 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\urls.py changed, reloading.
INFO 2021-05-31 08:19:52,994 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-31 08:20:02,227 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-31 08:20:06,912 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-31 08:20:06,951 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-31 08:20:06,952 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-31 08:20:14,563 basehttp 154 "GET /users/capycha/ HTTP/1.1" 200 105
INFO 2021-05-31 08:20:20,014 basehttp 154 "OPTIONS /users/capycha HTTP/1.1" 200 0
ERROR 2021-05-31 08:20:20,207 log 228 Internal Server Error: /users/capycha
Traceback (most recent call last):
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\envs\luffy\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "E:\envs\luffy\lib\site-packages\django\middleware\common.py", line 53, in process_request
    path = self.get_full_path_with_slash(request)
  File "E:\envs\luffy\lib\site-packages\django\middleware\common.py", line 93, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to api.luffycity.cn:8001/users/capycha/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2021-05-31 08:20:20,208 basehttp 154 "POST /users/capycha HTTP/1.1" 500 70376
INFO 2021-05-31 08:20:22,219 basehttp 154 "GET /users/capycha/ HTTP/1.1" 200 105
INFO 2021-05-31 08:20:53,593 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-31 08:21:06,776 basehttp 154 "GET /users/capycha/ HTTP/1.1" 200 105
INFO 2021-05-31 08:21:11,639 basehttp 154 "OPTIONS /users/capycha/ HTTP/1.1" 200 0
INFO 2021-05-31 08:21:11,729 basehttp 154 "POST /users/capycha/ HTTP/1.1" 200 20
INFO 2021-05-31 08:21:11,733 basehttp 154 "OPTIONS /users/login/ HTTP/1.1" 200 0
INFO 2021-05-31 08:21:11,836 basehttp 154 "POST /users/login/ HTTP/1.1" 200 197
INFO 2021-05-31 08:21:11,873 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-31 08:21:11,899 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-31 08:21:11,903 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-31 08:26:59,165 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\urls.py changed, reloading.
INFO 2021-05-31 08:27:01,440 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-31 08:42:49,577 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\home\views.py changed, reloading.
INFO 2021-05-31 08:42:51,579 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-31 08:46:58,721 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\views.py changed, reloading.
INFO 2021-05-31 08:47:00,214 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-31 08:47:31,619 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\views.py changed, reloading.
INFO 2021-05-31 08:47:33,324 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-31 08:47:45,032 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\views.py changed, reloading.
INFO 2021-05-31 08:47:46,560 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-31 09:13:47,235 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-31 09:13:47,239 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-31 09:13:47,240 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-31 09:14:40,642 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\serializers.py changed, reloading.
INFO 2021-05-31 09:14:42,777 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-05-31 09:14:45,439 log 228 Not Found: /
WARNING 2021-05-31 09:14:45,439 basehttp 154 "GET / HTTP/1.1" 404 2372
WARNING 2021-05-31 09:14:45,511 log 228 Not Found: /favicon.ico
WARNING 2021-05-31 09:14:45,512 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2423
INFO 2021-05-31 09:14:49,652 basehttp 154 "GET /xadmin HTTP/1.1" 301 0
INFO 2021-05-31 09:14:49,701 basehttp 154 "GET /xadmin/ HTTP/1.1" 200 4358
INFO 2021-05-31 09:14:49,728 basehttp 154 "GET /static/xadmin/css/xadmin.plugins.css HTTP/1.1" 200 175
INFO 2021-05-31 09:14:49,730 basehttp 154 "GET /static/xadmin/css/themes/bootstrap-xadmin.css HTTP/1.1" 200 1888
INFO 2021-05-31 09:14:49,731 basehttp 154 "GET /static/xadmin/css/xadmin.responsive.css HTTP/1.1" 200 4361
INFO 2021-05-31 09:14:49,735 basehttp 154 "GET /static/xadmin/vendor/font-awesome/css/font-awesome.css HTTP/1.1" 200 21658
INFO 2021-05-31 09:14:49,735 basehttp 154 "GET /static/xadmin/css/xadmin.main.css HTTP/1.1" 200 8376
INFO 2021-05-31 09:14:49,739 basehttp 154 "GET /static/xadmin/vendor/bootstrap/css/bootstrap.css HTTP/1.1" 200 126432
INFO 2021-05-31 09:14:49,742 basehttp 154 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.core.js HTTP/1.1" 200 8195
INFO 2021-05-31 09:14:49,751 basehttp 154 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.widget.js HTTP/1.1" 200 15069
INFO 2021-05-31 09:14:49,751 basehttp 154 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.mouse.js HTTP/1.1" 200 4561
INFO 2021-05-31 09:14:49,756 basehttp 154 "GET /xadmin/jsi18n/ HTTP/1.1" 200 4365
INFO 2021-05-31 09:14:49,758 basehttp 154 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.sortable.js HTTP/1.1" 200 42543
INFO 2021-05-31 09:14:49,761 basehttp 154 "GET /static/xadmin/vendor/bootstrap/js/bootstrap.js HTTP/1.1" 200 58327
INFO 2021-05-31 09:14:49,761 basehttp 154 "GET /static/xadmin/vendor/jquery/jquery.js HTTP/1.1" 200 240196
INFO 2021-05-31 09:14:49,762 basehttp 154 "GET /static/xadmin/js/xadmin.main.js HTTP/1.1" 200 3401
INFO 2021-05-31 09:14:49,763 basehttp 154 "GET /static/xadmin/js/xadmin.responsive.js HTTP/1.1" 200 4165
INFO 2021-05-31 09:14:49,764 basehttp 154 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.effect.js HTTP/1.1" 200 31918
INFO 2021-05-31 09:14:49,765 basehttp 154 "GET /static/xadmin/js/xadmin.plugin.themes.js HTTP/1.1" 200 3489
INFO 2021-05-31 09:14:49,812 basehttp 154 "GET /static/xadmin/vendor/font-awesome/fonts/fontawesome-webfont.woff?v=4.0.3 HTTP/1.1" 200 44432
INFO 2021-05-31 09:14:57,254 basehttp 154 "POST /xadmin/ HTTP/1.1" 302 0
INFO 2021-05-31 09:14:58,702 basehttp 154 "GET /xadmin/ HTTP/1.1" 200 13597
INFO 2021-05-31 09:14:58,726 basehttp 154 "GET /static/xadmin/css/xadmin.page.dashboard.css HTTP/1.1" 200 790
INFO 2021-05-31 09:14:58,727 basehttp 154 "GET /static/xadmin/js/xadmin.page.dashboard.js HTTP/1.1" 200 3208
INFO 2021-05-31 09:14:58,727 basehttp 154 "GET /static/xadmin/js/xadmin.plugin.portal.js HTTP/1.1" 200 1000
ERROR 2021-05-31 09:14:58,907 log 228 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 350, in i18n_javascript
    return JavaScriptCatalog.as_view(packages=['django.contrib.admin'])(request)
  File "E:\envs\luffy\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\i18n.py", line 201, in get
    self.translation = DjangoTranslation(locale, domain=domain, localedirs=paths)
  File "E:\envs\luffy\lib\site-packages\django\utils\translation\trans_real.py", line 151, in __init__
    translation = self._new_gnu_trans(localedir)
  File "E:\envs\luffy\lib\site-packages\django\utils\translation\trans_real.py", line 180, in _new_gnu_trans
    fallback=use_null_fallback,
  File "c:\python3.7\lib\gettext.py", line 533, in translation
    t = _translations.setdefault(key, class_(fp))
  File "c:\python3.7\lib\gettext.py", line 260, in __init__
    self._parse(fp)
  File "c:\python3.7\lib\gettext.py", line 353, in _parse
    magic = unpack('<I', buf[:4])[0]
struct.error: unpack requires a buffer of 4 bytes
ERROR 2021-05-31 09:14:58,912 basehttp 154 "GET /xadmin/jsi18n/ HTTP/1.1" 500 119785
INFO 2021-05-31 09:15:03,299 basehttp 154 "GET /xadmin/users/user/ HTTP/1.1" 200 33661
INFO 2021-05-31 09:15:03,320 basehttp 154 "GET /static/xadmin/css/xadmin.form.css HTTP/1.1" 200 3763
INFO 2021-05-31 09:15:03,320 basehttp 154 "GET /static/xadmin/js/xadmin.plugin.actions.js HTTP/1.1" 200 4198
INFO 2021-05-31 09:15:03,321 basehttp 154 "GET /static/xadmin/js/xadmin.plugin.filters.js HTTP/1.1" 200 1990
INFO 2021-05-31 09:15:03,321 basehttp 154 "GET /static/xadmin/js/xadmin.plugin.details.js HTTP/1.1" 200 2319
INFO 2021-05-31 09:15:03,322 basehttp 154 "GET /static/xadmin/js/xadmin.plugin.bookmark.js HTTP/1.1" 200 529
INFO 2021-05-31 09:15:03,337 basehttp 154 "GET /static/xadmin/js/xadmin.page.list.js HTTP/1.1" 200 1105
INFO 2021-05-31 09:15:03,338 basehttp 154 "GET /static/xadmin/js/xadmin.page.form.js HTTP/1.1" 200 1948
ERROR 2021-05-31 09:15:03,367 log 228 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 350, in i18n_javascript
    return JavaScriptCatalog.as_view(packages=['django.contrib.admin'])(request)
  File "E:\envs\luffy\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\i18n.py", line 201, in get
    self.translation = DjangoTranslation(locale, domain=domain, localedirs=paths)
  File "E:\envs\luffy\lib\site-packages\django\utils\translation\trans_real.py", line 151, in __init__
    translation = self._new_gnu_trans(localedir)
  File "E:\envs\luffy\lib\site-packages\django\utils\translation\trans_real.py", line 180, in _new_gnu_trans
    fallback=use_null_fallback,
  File "c:\python3.7\lib\gettext.py", line 533, in translation
    t = _translations.setdefault(key, class_(fp))
  File "c:\python3.7\lib\gettext.py", line 260, in __init__
    self._parse(fp)
  File "c:\python3.7\lib\gettext.py", line 353, in _parse
    magic = unpack('<I', buf[:4])[0]
struct.error: unpack requires a buffer of 4 bytes
ERROR 2021-05-31 09:15:03,369 basehttp 154 "GET /xadmin/jsi18n/ HTTP/1.1" 500 119796
INFO 2021-05-31 09:15:06,251 basehttp 154 "GET /xadmin/users/user/1/update/ HTTP/1.1" 200 30679
INFO 2021-05-31 09:15:06,272 basehttp 154 "GET /static/xadmin/vendor/bootstrap-datepicker/css/datepicker.css HTTP/1.1" 200 10225
INFO 2021-05-31 09:15:06,272 basehttp 154 "GET /static/xadmin/vendor/bootstrap-image-gallery/css/bootstrap-image-gallery.css HTTP/1.1" 200 3339
INFO 2021-05-31 09:15:06,272 basehttp 154 "GET /static/xadmin/css/xadmin.widget.select-transfer.css HTTP/1.1" 200 2317
INFO 2021-05-31 09:15:06,273 basehttp 154 "GET /static/xadmin/vendor/bootstrap-clockpicker/bootstrap-clockpicker.css HTTP/1.1" 200 3729
INFO 2021-05-31 09:15:06,279 basehttp 154 "GET /static/xadmin/vendor/load-image/load-image.js HTTP/1.1" 200 8309
INFO 2021-05-31 09:15:06,284 basehttp 154 "GET /static/xadmin/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js HTTP/1.1" 200 32656
INFO 2021-05-31 09:15:06,299 basehttp 154 "GET /static/xadmin/js/xadmin.plugin.quick-form.js HTTP/1.1" 200 7546
ERROR 2021-05-31 09:15:06,327 log 228 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 350, in i18n_javascript
    return JavaScriptCatalog.as_view(packages=['django.contrib.admin'])(request)
  File "E:\envs\luffy\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\i18n.py", line 201, in get
    self.translation = DjangoTranslation(locale, domain=domain, localedirs=paths)
  File "E:\envs\luffy\lib\site-packages\django\utils\translation\trans_real.py", line 151, in __init__
    translation = self._new_gnu_trans(localedir)
  File "E:\envs\luffy\lib\site-packages\django\utils\translation\trans_real.py", line 180, in _new_gnu_trans
    fallback=use_null_fallback,
  File "c:\python3.7\lib\gettext.py", line 533, in translation
    t = _translations.setdefault(key, class_(fp))
  File "c:\python3.7\lib\gettext.py", line 260, in __init__
    self._parse(fp)
  File "c:\python3.7\lib\gettext.py", line 353, in _parse
    magic = unpack('<I', buf[:4])[0]
struct.error: unpack requires a buffer of 4 bytes
INFO 2021-05-31 09:15:06,327 basehttp 154 "GET /static/xadmin/js/xadmin.widget.select-transfer.js HTTP/1.1" 200 8214
ERROR 2021-05-31 09:15:06,329 basehttp 154 "GET /xadmin/jsi18n/ HTTP/1.1" 500 119805
INFO 2021-05-31 09:15:06,333 basehttp 154 "GET /static/xadmin/vendor/bootstrap-image-gallery/js/bootstrap-image-gallery.js HTTP/1.1" 200 15611
INFO 2021-05-31 09:15:06,339 basehttp 154 "GET /media/avatar/shuaige.jpg HTTP/1.1" 200 14266
INFO 2021-05-31 09:15:06,339 basehttp 154 "GET /static/xadmin/js/xadmin.widget.datetime.js HTTP/1.1" 200 2979
INFO 2021-05-31 09:15:06,339 basehttp 154 "GET /static/xadmin/vendor/bootstrap-clockpicker/bootstrap-clockpicker.js HTTP/1.1" 200 21112
INFO 2021-05-31 09:15:20,795 basehttp 154 "POST /xadmin/users/user/1/update/ HTTP/1.1" 302 0
INFO 2021-05-31 09:15:20,866 basehttp 154 "GET /xadmin/users/user/ HTTP/1.1" 200 33901
ERROR 2021-05-31 09:15:20,931 log 228 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 350, in i18n_javascript
    return JavaScriptCatalog.as_view(packages=['django.contrib.admin'])(request)
  File "E:\envs\luffy\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\i18n.py", line 201, in get
    self.translation = DjangoTranslation(locale, domain=domain, localedirs=paths)
  File "E:\envs\luffy\lib\site-packages\django\utils\translation\trans_real.py", line 151, in __init__
    translation = self._new_gnu_trans(localedir)
  File "E:\envs\luffy\lib\site-packages\django\utils\translation\trans_real.py", line 180, in _new_gnu_trans
    fallback=use_null_fallback,
  File "c:\python3.7\lib\gettext.py", line 533, in translation
    t = _translations.setdefault(key, class_(fp))
  File "c:\python3.7\lib\gettext.py", line 260, in __init__
    self._parse(fp)
  File "c:\python3.7\lib\gettext.py", line 353, in _parse
    magic = unpack('<I', buf[:4])[0]
struct.error: unpack requires a buffer of 4 bytes
ERROR 2021-05-31 09:15:20,933 basehttp 154 "GET /xadmin/jsi18n/ HTTP/1.1" 500 119796
INFO 2021-05-31 09:15:33,074 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-31 09:15:33,080 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-31 09:15:33,086 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-31 09:15:43,001 basehttp 154 "GET /users/capycha/ HTTP/1.1" 200 105
INFO 2021-05-31 09:15:48,180 basehttp 154 "OPTIONS /users/capycha/ HTTP/1.1" 200 0
INFO 2021-05-31 09:15:48,379 basehttp 154 "POST /users/capycha/ HTTP/1.1" 200 20
INFO 2021-05-31 09:15:48,383 basehttp 154 "OPTIONS /users/login/ HTTP/1.1" 200 0
INFO 2021-05-31 09:15:48,472 basehttp 154 "POST /users/login/ HTTP/1.1" 200 197
INFO 2021-05-31 09:15:48,510 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-31 09:15:48,525 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-31 09:15:48,525 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-31 10:39:36,458 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-31 10:42:02,491 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\serializers.py changed, reloading.
INFO 2021-05-31 10:42:04,475 autoreload 597 Watching for file changes with StatReloader
ERROR 2021-05-31 10:42:09,934 log 228 Internal Server Error: /users/register/
Traceback (most recent call last):
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\envs\luffy\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\envs\luffy\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\envs\luffy\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\rest_framework\generics.py", line 190, in post
    return self.create(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\rest_framework\mixins.py", line 17, in create
    serializer = self.get_serializer(data=request.data)
  File "E:\envs\luffy\lib\site-packages\rest_framework\generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
TypeError: 'UserModelSerializer' object is not callable
ERROR 2021-05-31 10:42:09,936 basehttp 154 "POST /users/register/ HTTP/1.1" 500 19660
INFO 2021-05-31 10:44:57,884 autoreload 597 Watching for file changes with StatReloader
ERROR 2021-05-31 10:44:58,998 log 228 Internal Server Error: /users/register/
Traceback (most recent call last):
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "E:\envs\luffy\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "E:\envs\luffy\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "E:\envs\luffy\lib\site-packages\rest_framework\renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "E:\envs\luffy\lib\site-packages\rest_framework\renderers.py", line 655, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "E:\envs\luffy\lib\site-packages\rest_framework\renderers.py", line 554, in get_raw_data_form
    serializer = view.get_serializer()
  File "E:\envs\luffy\lib\site-packages\rest_framework\generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
TypeError: 'UserModelSerializer' object is not callable
ERROR 2021-05-31 10:44:59,000 basehttp 154 "GET /users/register/ HTTP/1.1" 500 99095
WARNING 2021-05-31 10:44:59,183 log 228 Not Found: /favicon.ico
WARNING 2021-05-31 10:44:59,183 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2423
INFO 2021-05-31 10:46:21,895 autoreload 597 Watching for file changes with StatReloader
ERROR 2021-05-31 10:46:38,466 log 228 Internal Server Error: /users/register/
Traceback (most recent call last):
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\envs\luffy\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\envs\luffy\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\envs\luffy\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\rest_framework\generics.py", line 190, in post
    return self.create(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\rest_framework\mixins.py", line 17, in create
    serializer = self.get_serializer(data=request.data)
  File "E:\envs\luffy\lib\site-packages\rest_framework\generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
TypeError: 'UserModelSerializer' object is not callable
ERROR 2021-05-31 10:46:38,468 basehttp 154 "POST /users/register/ HTTP/1.1" 500 19660
INFO 2021-05-31 10:50:56,721 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-05-31 10:51:00,640 log 228 Bad Request: /users/register/
WARNING 2021-05-31 10:51:00,641 basehttp 154 "POST /users/register/ HTTP/1.1" 400 55
INFO 2021-05-31 10:51:22,334 basehttp 154 "POST /users/register/ HTTP/1.1" 201 38
INFO 2021-05-31 10:54:17,916 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\serializers.py changed, reloading.
INFO 2021-05-31 10:54:19,408 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-05-31 10:54:20,132 log 228 Method Not Allowed: /users/register/
WARNING 2021-05-31 10:54:20,133 basehttp 154 "GET /users/register/ HTTP/1.1" 405 7858
INFO 2021-05-31 10:54:20,162 basehttp 154 "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
INFO 2021-05-31 10:54:20,163 basehttp 154 "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
INFO 2021-05-31 10:54:20,163 basehttp 154 "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1152
INFO 2021-05-31 10:54:20,164 basehttp 154 "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
INFO 2021-05-31 10:54:20,165 basehttp 154 "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
INFO 2021-05-31 10:54:20,165 basehttp 154 "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
INFO 2021-05-31 10:54:20,171 basehttp 154 "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
INFO 2021-05-31 10:54:20,174 basehttp 154 "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
INFO 2021-05-31 10:54:20,175 basehttp 154 "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
INFO 2021-05-31 10:54:20,175 basehttp 154 "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
INFO 2021-05-31 10:54:20,182 basehttp 154 "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
WARNING 2021-05-31 10:54:34,200 log 228 Bad Request: /users/register/
WARNING 2021-05-31 10:54:34,200 basehttp 154 "POST /users/register/ HTTP/1.1" 400 7894
INFO 2021-05-31 11:03:22,355 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\serializers.py changed, reloading.
INFO 2021-05-31 11:03:23,937 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-31 11:03:42,213 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\serializers.py changed, reloading.
INFO 2021-05-31 11:03:43,662 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-31 11:10:34,385 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-31 11:10:40,475 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-31 11:10:40,589 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-31 11:10:40,591 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-31 11:10:53,356 basehttp 154 "OPTIONS /users/register/ HTTP/1.1" 200 0
WARNING 2021-05-31 11:10:53,361 log 228 Bad Request: /users/register/
WARNING 2021-05-31 11:10:53,362 basehttp 154 "POST /users/register/ HTTP/1.1" 400 65
WARNING 2021-05-31 11:11:09,221 log 228 Bad Request: /users/register/
WARNING 2021-05-31 11:11:09,222 basehttp 154 "POST /users/register/ HTTP/1.1" 400 65
INFO 2021-05-31 11:17:13,278 autoreload 217 E:\luffy\luffyapi\luffyapi\settings\dev.py changed, reloading.
INFO 2021-05-31 11:17:15,257 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-31 11:21:12,450 autoreload 217 E:\luffy\luffyapi\luffyapi\settings\dev.py changed, reloading.
INFO 2021-05-31 11:21:16,322 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-31 11:21:46,112 basehttp 154 "OPTIONS /users/register HTTP/1.1" 200 0
ERROR 2021-05-31 11:21:46,242 log 228 Internal Server Error: /users/register
Traceback (most recent call last):
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\envs\luffy\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "E:\envs\luffy\lib\site-packages\django\middleware\common.py", line 53, in process_request
    path = self.get_full_path_with_slash(request)
  File "E:\envs\luffy\lib\site-packages\django\middleware\common.py", line 93, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to api.luffycity.cn:8001/users/register/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2021-05-31 11:21:46,243 basehttp 154 "POST /users/register HTTP/1.1" 500 70391
ERROR 2021-05-31 11:22:11,223 log 228 Internal Server Error: /users/register/
Traceback (most recent call last):
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\envs\luffy\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\envs\luffy\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\envs\luffy\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\rest_framework\generics.py", line 190, in post
    return self.create(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "E:\envs\luffy\lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "E:\envs\luffy\lib\site-packages\rest_framework\serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "E:\luffy\luffyapi\luffyapi\apps\users\serializers.py", line 64, in create
    jwt_encode_handler = api_settings.JWT_ENCEDE_HANDLER
  File "E:\envs\luffy\lib\site-packages\rest_framework\settings.py", line 214, in __getattr__
    raise AttributeError("Invalid API setting: '%s'" % attr)
AttributeError: Invalid API setting: 'JWT_ENCEDE_HANDLER'
ERROR 2021-05-31 11:22:11,227 basehttp 154 "POST /users/register/ HTTP/1.1" 500 20269
ERROR 2021-05-31 11:27:01,828 log 228 Internal Server Error: /users/register/
Traceback (most recent call last):
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\envs\luffy\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\envs\luffy\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\envs\luffy\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\rest_framework\generics.py", line 190, in post
    return self.create(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "E:\envs\luffy\lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "E:\envs\luffy\lib\site-packages\rest_framework\serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "E:\luffy\luffyapi\luffyapi\apps\users\serializers.py", line 64, in create
    jwt_encode_handler = api_settings.JWT_ENCEDE_HANDLER
  File "E:\envs\luffy\lib\site-packages\rest_framework\settings.py", line 214, in __getattr__
    raise AttributeError("Invalid API setting: '%s'" % attr)
AttributeError: Invalid API setting: 'JWT_ENCEDE_HANDLER'
ERROR 2021-05-31 11:27:01,830 basehttp 154 "POST /users/register/ HTTP/1.1" 500 20269
INFO 2021-05-31 11:27:45,220 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\serializers.py changed, reloading.
INFO 2021-05-31 11:27:46,762 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-05-31 11:28:54,049 log 228 Bad Request: /users/register/
WARNING 2021-05-31 11:28:54,050 basehttp 154 "POST /users/register/ HTTP/1.1" 400 55
INFO 2021-05-31 11:29:31,622 basehttp 154 "POST /users/register/ HTTP/1.1" 201 225
WARNING 2021-05-31 11:29:49,529 log 228 Bad Request: /users/register/
WARNING 2021-05-31 11:29:49,529 basehttp 154 "POST /users/register/ HTTP/1.1" 400 55
INFO 2021-05-31 11:30:45,845 basehttp 154 "GET /users/capycha/ HTTP/1.1" 200 105
INFO 2021-05-31 11:30:51,788 basehttp 154 "OPTIONS /users/capycha/ HTTP/1.1" 200 0
INFO 2021-05-31 11:30:51,887 basehttp 154 "POST /users/capycha/ HTTP/1.1" 200 20
INFO 2021-05-31 11:30:51,891 basehttp 154 "OPTIONS /users/login/ HTTP/1.1" 200 0
INFO 2021-05-31 11:30:51,987 basehttp 154 "POST /users/login/ HTTP/1.1" 200 188
INFO 2021-05-31 11:30:52,056 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-31 11:30:52,088 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-31 11:30:52,094 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-31 11:41:22,174 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\urls.py changed, reloading.
INFO 2021-05-31 11:41:23,880 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-05-31 11:43:09,323 log 228 Not Found: /users/mobile//
WARNING 2021-05-31 11:43:09,324 basehttp 154 "GET /users/mobile// HTTP/1.1" 404 2998
WARNING 2021-05-31 11:43:34,381 log 228 Not Found: /users/mobile//
WARNING 2021-05-31 11:43:34,382 basehttp 154 "GET /users/mobile// HTTP/1.1" 404 2998
INFO 2021-05-31 14:03:07,632 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-05-31 14:03:14,205 log 228 Not Found: /users/mobile//
WARNING 2021-05-31 14:03:14,205 basehttp 154 "GET /users/mobile// HTTP/1.1" 404 2998
INFO 2021-05-31 14:03:16,550 basehttp 154 "OPTIONS /users/register/ HTTP/1.1" 200 0
WARNING 2021-05-31 14:03:16,558 log 228 Bad Request: /users/register/
WARNING 2021-05-31 14:03:16,559 basehttp 154 "POST /users/register/ HTTP/1.1" 400 131
INFO 2021-05-31 14:07:21,265 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\views.py changed, reloading.
INFO 2021-05-31 14:07:22,821 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-05-31 14:07:36,663 log 228 Not Found: /users/mobile//
WARNING 2021-05-31 14:07:36,663 basehttp 154 "GET /users/mobile// HTTP/1.1" 404 2999
WARNING 2021-05-31 14:07:40,404 log 228 Not Found: /users/mobile/1515/
WARNING 2021-05-31 14:07:40,404 basehttp 154 "GET /users/mobile/1515/ HTTP/1.1" 404 3011
WARNING 2021-05-31 14:07:40,494 log 228 Bad Request: /users/register/
WARNING 2021-05-31 14:07:40,495 basehttp 154 "POST /users/register/ HTTP/1.1" 400 89
WARNING 2021-05-31 14:07:44,604 log 228 Not Found: /users/mobile/1515/
WARNING 2021-05-31 14:07:44,604 basehttp 154 "GET /users/mobile/1515/ HTTP/1.1" 404 3011
WARNING 2021-05-31 14:08:02,185 log 228 Not Found: /users/mobile/1515216648/
WARNING 2021-05-31 14:08:02,185 basehttp 154 "GET /users/mobile/1515216648/ HTTP/1.1" 404 3029
WARNING 2021-05-31 14:08:02,269 log 228 Bad Request: /users/register/
WARNING 2021-05-31 14:08:02,269 basehttp 154 "POST /users/register/ HTTP/1.1" 400 89
INFO 2021-05-31 14:14:10,819 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-31 14:14:37,682 basehttp 154 "GET /users/mobile/15833732708/ HTTP/1.1" 200 49
WARNING 2021-05-31 14:14:48,402 log 228 Not Found: /users/mobile/11485465/
WARNING 2021-05-31 14:14:48,402 basehttp 154 "GET /users/mobile/11485465/ HTTP/1.1" 404 3023
WARNING 2021-05-31 14:14:50,560 log 228 Not Found: /users/mobile/11485465/
WARNING 2021-05-31 14:14:50,560 basehttp 154 "GET /users/mobile/11485465/ HTTP/1.1" 404 3023
WARNING 2021-05-31 14:14:50,629 log 228 Bad Request: /users/register/
WARNING 2021-05-31 14:14:50,629 basehttp 154 "POST /users/register/ HTTP/1.1" 400 89
INFO 2021-05-31 14:14:57,725 basehttp 154 "GET /users/mobile/13315932145/ HTTP/1.1" 200 49
INFO 2021-05-31 14:15:03,998 basehttp 154 "GET /users/mobile/17732917776/ HTTP/1.1" 200 49
INFO 2021-05-31 14:15:11,204 basehttp 154 "GET /users/mobile/17732917776/ HTTP/1.1" 200 49
INFO 2021-05-31 14:15:51,550 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\utils.py changed, reloading.
INFO 2021-05-31 14:15:53,071 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-31 14:16:13,917 basehttp 154 "GET /users/mobile/17732917776/ HTTP/1.1" 200 49
INFO 2021-05-31 14:16:14,832 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\views.py changed, reloading.
INFO 2021-05-31 14:16:16,289 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-31 14:16:16,777 basehttp 154 "GET /users/mobile/17732917776/ HTTP/1.1" 200 49
INFO 2021-05-31 14:17:16,342 basehttp 154 "GET /users/mobile/17732917776/ HTTP/1.1" 200 49
INFO 2021-05-31 14:18:10,576 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-31 14:18:13,734 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-31 14:18:13,801 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-31 14:18:13,802 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-31 14:18:27,190 basehttp 154 "GET /users/capycha/ HTTP/1.1" 200 105
INFO 2021-05-31 14:18:33,236 basehttp 154 "OPTIONS /users/capycha/ HTTP/1.1" 200 0
INFO 2021-05-31 14:18:33,327 basehttp 154 "POST /users/capycha/ HTTP/1.1" 200 20
INFO 2021-05-31 14:18:33,332 basehttp 154 "OPTIONS /users/login/ HTTP/1.1" 200 0
WARNING 2021-05-31 14:18:33,436 log 228 Bad Request: /users/login/
WARNING 2021-05-31 14:18:33,437 basehttp 154 "POST /users/login/ HTTP/1.1" 400 68
INFO 2021-05-31 14:18:40,207 basehttp 154 "GET /users/capycha/ HTTP/1.1" 200 105
INFO 2021-05-31 14:18:44,965 basehttp 154 "POST /users/capycha/ HTTP/1.1" 200 20
INFO 2021-05-31 14:18:45,065 basehttp 154 "POST /users/login/ HTTP/1.1" 200 188
INFO 2021-05-31 14:18:45,094 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-31 14:18:45,121 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-31 14:18:45,121 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-31 14:19:09,247 basehttp 154 "GET /users/mobile/13315932145/ HTTP/1.1" 200 49
INFO 2021-05-31 14:19:12,302 basehttp 154 "GET /users/mobile/13315932145/ HTTP/1.1" 200 49
INFO 2021-05-31 14:29:24,383 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\utils.py changed, reloading.
INFO 2021-05-31 14:29:25,946 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-31 14:29:26,373 basehttp 154 "GET /users/mobile/13315932145/ HTTP/1.1" 200 49
WARNING 2021-05-31 14:29:26,380 log 228 Bad Request: /users/register/
WARNING 2021-05-31 14:29:26,381 basehttp 154 "POST /users/register/ HTTP/1.1" 400 89
WARNING 2021-05-31 14:29:54,391 log 228 Bad Request: /users/register/
WARNING 2021-05-31 14:29:54,392 basehttp 154 "POST /users/register/ HTTP/1.1" 400 89
INFO 2021-05-31 14:29:55,205 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\urls.py changed, reloading.
INFO 2021-05-31 14:29:56,761 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-31 14:30:39,012 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\urls.py changed, reloading.
INFO 2021-05-31 14:30:40,574 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-05-31 14:30:43,022 log 228 Bad Request: /users/register/
WARNING 2021-05-31 14:30:43,022 basehttp 154 "POST /users/register/ HTTP/1.1" 400 89
INFO 2021-05-31 14:30:58,029 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\urls.py changed, reloading.
INFO 2021-05-31 14:30:59,444 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-05-31 14:31:01,624 log 228 Not Found: /users/mobile/1569874563/
WARNING 2021-05-31 14:31:01,625 basehttp 154 "GET /users/mobile/1569874563/ HTTP/1.1" 404 3029
INFO 2021-05-31 14:31:10,880 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-31 14:31:35,896 basehttp 154 "GET /users/mobile/17896541235/ HTTP/1.1" 200 49
WARNING 2021-05-31 14:31:43,776 log 228 Bad Request: /users/mobile/17732917776/
WARNING 2021-05-31 14:31:43,776 basehttp 154 "GET /users/mobile/17732917776/ HTTP/1.1" 400 43
WARNING 2021-05-31 14:32:44,959 log 228 Bad Request: /users/mobile/17732917776/
WARNING 2021-05-31 14:32:44,960 basehttp 154 "GET /users/mobile/17732917776/ HTTP/1.1" 400 43
WARNING 2021-05-31 14:32:48,116 log 228 Bad Request: /users/mobile/17732917776/
WARNING 2021-05-31 14:32:48,116 basehttp 154 "GET /users/mobile/17732917776/ HTTP/1.1" 400 43
WARNING 2021-05-31 14:32:51,340 log 228 Bad Request: /users/mobile/17732917776/
WARNING 2021-05-31 14:32:51,341 basehttp 154 "GET /users/mobile/17732917776/ HTTP/1.1" 400 43
WARNING 2021-05-31 14:33:00,417 log 228 Bad Request: /users/register/
WARNING 2021-05-31 14:33:00,417 basehttp 154 "POST /users/register/ HTTP/1.1" 400 89
INFO 2021-05-31 14:34:53,304 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-31 14:34:53,383 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-31 14:34:53,387 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-31 14:35:04,134 basehttp 154 "GET /users/mobile/15833732708/ HTTP/1.1" 200 49
INFO 2021-05-31 14:35:11,280 basehttp 154 "POST /users/register/ HTTP/1.1" 201 225
INFO 2021-05-31 14:35:11,315 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-31 14:35:11,322 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-31 14:35:11,323 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-31 14:35:31,571 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-31 14:35:31,625 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-31 14:35:31,634 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
WARNING 2021-05-31 14:35:55,870 log 228 Not Found: /users/mobile//
WARNING 2021-05-31 14:35:55,870 basehttp 154 "GET /users/mobile// HTTP/1.1" 404 2999
INFO 2021-05-31 14:36:02,597 basehttp 154 "GET /users/mobile/15833732708/ HTTP/1.1" 200 49
INFO 2021-05-31 14:36:14,543 basehttp 154 "POST /users/register/ HTTP/1.1" 201 225
INFO 2021-05-31 14:36:14,580 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-31 14:36:14,601 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-31 14:36:14,602 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-31 14:36:41,254 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-31 14:36:41,305 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-31 14:36:41,308 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-31 14:36:48,831 basehttp 154 "GET /users/mobile/15512459510/ HTTP/1.1" 200 49
INFO 2021-05-31 14:36:55,393 basehttp 154 "POST /users/register/ HTTP/1.1" 201 225
INFO 2021-05-31 14:36:55,416 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-31 14:36:55,431 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-31 14:36:55,434 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-31 14:37:11,780 basehttp 154 "GET /users/capycha/ HTTP/1.1" 200 105
INFO 2021-05-31 14:37:18,625 basehttp 154 "POST /users/capycha/ HTTP/1.1" 200 20
INFO 2021-05-31 14:37:18,719 basehttp 154 "POST /users/login/ HTTP/1.1" 200 188
INFO 2021-05-31 14:37:18,750 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-31 14:37:18,750 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-31 14:37:18,750 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
WARNING 2021-05-31 14:40:05,062 log 228 Bad Request: /users/register/
WARNING 2021-05-31 14:40:05,063 basehttp 154 "POST /users/register/ HTTP/1.1" 400 131
WARNING 2021-05-31 14:40:17,815 log 228 Bad Request: /users/register/
WARNING 2021-05-31 14:40:17,815 basehttp 154 "POST /users/register/ HTTP/1.1" 400 131
INFO 2021-05-31 14:42:04,297 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\serializers.py changed, reloading.
INFO 2021-05-31 14:42:06,124 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-05-31 14:44:33,177 log 228 Bad Request: /users/register/
WARNING 2021-05-31 14:44:33,178 basehttp 154 "POST /users/register/ HTTP/1.1" 400 131
INFO 2021-05-31 14:57:27,610 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-31 14:57:27,639 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-31 14:57:27,641 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-31 14:57:30,430 basehttp 154 "OPTIONS /users/register/ HTTP/1.1" 200 0
WARNING 2021-05-31 14:57:30,435 log 228 Bad Request: /users/register/
WARNING 2021-05-31 14:57:30,435 basehttp 154 "POST /users/register/ HTTP/1.1" 400 131
WARNING 2021-05-31 14:57:58,053 log 228 Bad Request: /users/register/
WARNING 2021-05-31 14:57:58,053 basehttp 154 "POST /users/register/ HTTP/1.1" 400 131
WARNING 2021-05-31 14:57:58,229 log 228 Bad Request: /users/register/
WARNING 2021-05-31 14:57:58,229 basehttp 154 "POST /users/register/ HTTP/1.1" 400 131
WARNING 2021-05-31 14:57:58,404 log 228 Bad Request: /users/register/
WARNING 2021-05-31 14:57:58,404 basehttp 154 "POST /users/register/ HTTP/1.1" 400 131
WARNING 2021-05-31 14:58:20,231 log 228 Bad Request: /users/register/
WARNING 2021-05-31 14:58:20,232 basehttp 154 "POST /users/register/ HTTP/1.1" 400 131
WARNING 2021-05-31 14:58:20,439 log 228 Bad Request: /users/register/
WARNING 2021-05-31 14:58:20,440 basehttp 154 "POST /users/register/ HTTP/1.1" 400 131
WARNING 2021-05-31 14:58:27,054 log 228 Bad Request: /users/register/
WARNING 2021-05-31 14:58:27,055 basehttp 154 "POST /users/register/ HTTP/1.1" 400 131
WARNING 2021-05-31 14:58:36,989 log 228 Bad Request: /users/register/
WARNING 2021-05-31 14:58:36,990 basehttp 154 "POST /users/register/ HTTP/1.1" 400 131
WARNING 2021-05-31 14:59:57,304 log 228 Bad Request: /users/register/
WARNING 2021-05-31 14:59:57,305 basehttp 154 "POST /users/register/ HTTP/1.1" 400 131
WARNING 2021-05-31 15:02:37,910 log 228 Bad Request: /users/register/
WARNING 2021-05-31 15:02:37,911 basehttp 154 "POST /users/register/ HTTP/1.1" 400 131
WARNING 2021-05-31 15:04:42,918 log 228 Bad Request: /users/register/
WARNING 2021-05-31 15:04:42,918 basehttp 154 "POST /users/register/ HTTP/1.1" 400 131
INFO 2021-05-31 15:06:22,057 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-31 15:06:34,831 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-31 15:09:21,338 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\views.py changed, reloading.
INFO 2021-05-31 15:09:22,895 autoreload 597 Watching for file changes with StatReloader
INFO 2021-05-31 15:09:30,258 autoreload 217 E:\luffy\luffyapi\luffyapi\apps\users\serializers.py changed, reloading.
INFO 2021-05-31 15:09:31,807 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-05-31 15:09:48,191 log 228 Not Found: /users/mobile/12345678910/
WARNING 2021-05-31 15:09:48,191 basehttp 154 "GET /users/mobile/12345678910/ HTTP/1.1" 404 3032
WARNING 2021-05-31 15:09:52,076 log 228 Not Found: /users/mobile/12345678910/
WARNING 2021-05-31 15:09:52,076 basehttp 154 "GET /users/mobile/12345678910/ HTTP/1.1" 404 3032
WARNING 2021-05-31 15:10:08,616 log 228 Bad Request: /users/register/
WARNING 2021-05-31 15:10:08,616 basehttp 154 "POST /users/register/ HTTP/1.1" 400 45
WARNING 2021-05-31 15:10:11,229 log 228 Bad Request: /users/register/
WARNING 2021-05-31 15:10:11,229 basehttp 154 "POST /users/register/ HTTP/1.1" 400 61
WARNING 2021-05-31 15:10:17,229 log 228 Bad Request: /users/register/
WARNING 2021-05-31 15:10:17,230 basehttp 154 "POST /users/register/ HTTP/1.1" 400 49
WARNING 2021-05-31 15:10:23,432 log 228 Not Found: /users/mobile/12345678910/
WARNING 2021-05-31 15:10:23,432 basehttp 154 "GET /users/mobile/12345678910/ HTTP/1.1" 404 3032
WARNING 2021-05-31 15:10:24,641 log 228 Not Found: /users/mobile/12345678910/
WARNING 2021-05-31 15:10:24,641 basehttp 154 "GET /users/mobile/12345678910/ HTTP/1.1" 404 3032
WARNING 2021-05-31 15:16:54,301 log 228 Bad Request: /users/register/
WARNING 2021-05-31 15:16:54,302 basehttp 154 "POST /users/register/ HTTP/1.1" 400 131
WARNING 2021-05-31 15:16:57,591 log 228 Not Found: /users/mobile//
WARNING 2021-05-31 15:16:57,591 basehttp 154 "GET /users/mobile// HTTP/1.1" 404 2999
WARNING 2021-05-31 15:17:01,252 log 228 Not Found: /users/mobile//
WARNING 2021-05-31 15:17:01,253 basehttp 154 "GET /users/mobile// HTTP/1.1" 404 2999
WARNING 2021-05-31 15:17:01,338 log 228 Bad Request: /users/register/
WARNING 2021-05-31 15:17:01,339 basehttp 154 "POST /users/register/ HTTP/1.1" 400 131
WARNING 2021-05-31 15:17:42,311 log 228 Bad Request: /users/register/
WARNING 2021-05-31 15:17:42,311 basehttp 154 "POST /users/register/ HTTP/1.1" 400 131
WARNING 2021-05-31 15:18:27,184 log 228 Bad Request: /users/register/
WARNING 2021-05-31 15:18:27,185 basehttp 154 "POST /users/register/ HTTP/1.1" 400 131
WARNING 2021-05-31 15:20:20,410 log 228 Not Found: /users/mobile//
WARNING 2021-05-31 15:20:20,411 basehttp 154 "GET /users/mobile// HTTP/1.1" 404 2999
WARNING 2021-05-31 15:21:54,358 log 228 Bad Request: /users/register/
WARNING 2021-05-31 15:21:54,358 basehttp 154 "POST /users/register/ HTTP/1.1" 400 131
INFO 2021-05-31 15:22:18,226 basehttp 154 "GET /users/capycha/ HTTP/1.1" 200 105
INFO 2021-05-31 15:22:23,891 basehttp 154 "OPTIONS /users/capycha/ HTTP/1.1" 200 0
INFO 2021-05-31 15:22:23,980 basehttp 154 "POST /users/capycha/ HTTP/1.1" 200 20
INFO 2021-05-31 15:22:23,984 basehttp 154 "OPTIONS /users/login/ HTTP/1.1" 200 0
INFO 2021-05-31 15:22:24,091 basehttp 154 "POST /users/login/ HTTP/1.1" 200 197
INFO 2021-05-31 15:22:24,155 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-31 15:22:24,185 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-31 15:22:24,195 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-31 15:23:59,679 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-31 15:23:59,726 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-31 15:23:59,736 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-31 15:24:04,134 basehttp 154 "OPTIONS /users/register/ HTTP/1.1" 200 0
WARNING 2021-05-31 15:24:04,138 log 228 Bad Request: /users/register/
WARNING 2021-05-31 15:24:04,138 basehttp 154 "POST /users/register/ HTTP/1.1" 400 131
WARNING 2021-05-31 15:25:49,776 log 228 Bad Request: /users/register/
WARNING 2021-05-31 15:25:49,776 basehttp 154 "POST /users/register/ HTTP/1.1" 400 131
WARNING 2021-05-31 15:27:52,368 log 228 Not Found: /users/mobile//
WARNING 2021-05-31 15:27:52,369 basehttp 154 "GET /users/mobile// HTTP/1.1" 404 2999
WARNING 2021-05-31 15:27:58,767 log 228 Bad Request: /users/register/
WARNING 2021-05-31 15:27:58,767 basehttp 154 "POST /users/register/ HTTP/1.1" 400 131
INFO 2021-05-31 15:28:01,091 basehttp 154 "GET /users/capycha/ HTTP/1.1" 200 105
INFO 2021-05-31 15:28:07,927 basehttp 154 "OPTIONS /users/capycha/ HTTP/1.1" 200 0
INFO 2021-05-31 15:28:08,019 basehttp 154 "POST /users/capycha/ HTTP/1.1" 200 20
INFO 2021-05-31 15:28:08,024 basehttp 154 "OPTIONS /users/login/ HTTP/1.1" 200 0
WARNING 2021-05-31 15:28:08,027 log 228 Bad Request: /users/login/
WARNING 2021-05-31 15:28:08,027 basehttp 154 "POST /users/login/ HTTP/1.1" 400 89
INFO 2021-05-31 15:34:08,559 basehttp 154 "GET /users/capycha/ HTTP/1.1" 200 105
INFO 2021-05-31 15:34:23,135 basehttp 154 "POST /users/capycha/ HTTP/1.1" 200 20
INFO 2021-05-31 15:34:23,234 basehttp 154 "POST /users/login/ HTTP/1.1" 200 188
INFO 2021-05-31 15:34:23,303 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-31 15:34:23,320 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-31 15:34:23,338 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-31 15:34:35,623 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-05-31 15:34:37,885 log 228 Not Found: /
WARNING 2021-05-31 15:34:37,888 basehttp 154 "GET / HTTP/1.1" 404 2372
WARNING 2021-05-31 15:34:37,967 log 228 Not Found: /favicon.ico
WARNING 2021-05-31 15:34:37,968 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2423
INFO 2021-05-31 15:34:43,221 basehttp 154 "GET /xadmin/ HTTP/1.1" 200 13597
ERROR 2021-05-31 15:34:43,479 log 228 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 350, in i18n_javascript
    return JavaScriptCatalog.as_view(packages=['django.contrib.admin'])(request)
  File "E:\envs\luffy\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\i18n.py", line 201, in get
    self.translation = DjangoTranslation(locale, domain=domain, localedirs=paths)
  File "E:\envs\luffy\lib\site-packages\django\utils\translation\trans_real.py", line 151, in __init__
    translation = self._new_gnu_trans(localedir)
  File "E:\envs\luffy\lib\site-packages\django\utils\translation\trans_real.py", line 180, in _new_gnu_trans
    fallback=use_null_fallback,
  File "c:\python3.7\lib\gettext.py", line 533, in translation
    t = _translations.setdefault(key, class_(fp))
  File "c:\python3.7\lib\gettext.py", line 260, in __init__
    self._parse(fp)
  File "c:\python3.7\lib\gettext.py", line 353, in _parse
    magic = unpack('<I', buf[:4])[0]
struct.error: unpack requires a buffer of 4 bytes
ERROR 2021-05-31 15:34:43,481 basehttp 154 "GET /xadmin/jsi18n/ HTTP/1.1" 500 119785
INFO 2021-05-31 15:34:45,401 basehttp 154 "GET /xadmin/users/user/ HTTP/1.1" 200 41378
ERROR 2021-05-31 15:34:45,455 log 228 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 350, in i18n_javascript
    return JavaScriptCatalog.as_view(packages=['django.contrib.admin'])(request)
  File "E:\envs\luffy\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\i18n.py", line 201, in get
    self.translation = DjangoTranslation(locale, domain=domain, localedirs=paths)
  File "E:\envs\luffy\lib\site-packages\django\utils\translation\trans_real.py", line 151, in __init__
    translation = self._new_gnu_trans(localedir)
  File "E:\envs\luffy\lib\site-packages\django\utils\translation\trans_real.py", line 180, in _new_gnu_trans
    fallback=use_null_fallback,
  File "c:\python3.7\lib\gettext.py", line 533, in translation
    t = _translations.setdefault(key, class_(fp))
  File "c:\python3.7\lib\gettext.py", line 260, in __init__
    self._parse(fp)
  File "c:\python3.7\lib\gettext.py", line 353, in _parse
    magic = unpack('<I', buf[:4])[0]
struct.error: unpack requires a buffer of 4 bytes
ERROR 2021-05-31 15:34:45,455 basehttp 154 "GET /xadmin/jsi18n/ HTTP/1.1" 500 119796
INFO 2021-05-31 15:34:48,184 basehttp 154 "GET /xadmin/users/user/5/update/ HTTP/1.1" 200 30454
ERROR 2021-05-31 15:34:48,249 log 228 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 350, in i18n_javascript
    return JavaScriptCatalog.as_view(packages=['django.contrib.admin'])(request)
  File "E:\envs\luffy\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\i18n.py", line 201, in get
    self.translation = DjangoTranslation(locale, domain=domain, localedirs=paths)
  File "E:\envs\luffy\lib\site-packages\django\utils\translation\trans_real.py", line 151, in __init__
    translation = self._new_gnu_trans(localedir)
  File "E:\envs\luffy\lib\site-packages\django\utils\translation\trans_real.py", line 180, in _new_gnu_trans
    fallback=use_null_fallback,
  File "c:\python3.7\lib\gettext.py", line 533, in translation
    t = _translations.setdefault(key, class_(fp))
  File "c:\python3.7\lib\gettext.py", line 260, in __init__
    self._parse(fp)
  File "c:\python3.7\lib\gettext.py", line 353, in _parse
    magic = unpack('<I', buf[:4])[0]
struct.error: unpack requires a buffer of 4 bytes
ERROR 2021-05-31 15:34:48,249 basehttp 154 "GET /xadmin/jsi18n/ HTTP/1.1" 500 119805
INFO 2021-05-31 15:35:12,450 basehttp 154 "POST /xadmin/users/user/5/update/ HTTP/1.1" 200 30837
ERROR 2021-05-31 15:35:12,556 log 228 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 350, in i18n_javascript
    return JavaScriptCatalog.as_view(packages=['django.contrib.admin'])(request)
  File "E:\envs\luffy\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\i18n.py", line 201, in get
    self.translation = DjangoTranslation(locale, domain=domain, localedirs=paths)
  File "E:\envs\luffy\lib\site-packages\django\utils\translation\trans_real.py", line 151, in __init__
    translation = self._new_gnu_trans(localedir)
  File "E:\envs\luffy\lib\site-packages\django\utils\translation\trans_real.py", line 180, in _new_gnu_trans
    fallback=use_null_fallback,
  File "c:\python3.7\lib\gettext.py", line 533, in translation
    t = _translations.setdefault(key, class_(fp))
  File "c:\python3.7\lib\gettext.py", line 260, in __init__
    self._parse(fp)
  File "c:\python3.7\lib\gettext.py", line 353, in _parse
    magic = unpack('<I', buf[:4])[0]
struct.error: unpack requires a buffer of 4 bytes
ERROR 2021-05-31 15:35:12,558 basehttp 154 "GET /xadmin/jsi18n/ HTTP/1.1" 500 119805
INFO 2021-05-31 15:35:34,650 basehttp 154 "POST /xadmin/users/user/5/update/ HTTP/1.1" 302 0
INFO 2021-05-31 15:35:34,736 basehttp 154 "GET /xadmin/users/user/ HTTP/1.1" 200 41628
ERROR 2021-05-31 15:35:34,802 log 228 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 350, in i18n_javascript
    return JavaScriptCatalog.as_view(packages=['django.contrib.admin'])(request)
  File "E:\envs\luffy\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\i18n.py", line 201, in get
    self.translation = DjangoTranslation(locale, domain=domain, localedirs=paths)
  File "E:\envs\luffy\lib\site-packages\django\utils\translation\trans_real.py", line 151, in __init__
    translation = self._new_gnu_trans(localedir)
  File "E:\envs\luffy\lib\site-packages\django\utils\translation\trans_real.py", line 180, in _new_gnu_trans
    fallback=use_null_fallback,
  File "c:\python3.7\lib\gettext.py", line 533, in translation
    t = _translations.setdefault(key, class_(fp))
  File "c:\python3.7\lib\gettext.py", line 260, in __init__
    self._parse(fp)
  File "c:\python3.7\lib\gettext.py", line 353, in _parse
    magic = unpack('<I', buf[:4])[0]
struct.error: unpack requires a buffer of 4 bytes
ERROR 2021-05-31 15:35:34,804 basehttp 154 "GET /xadmin/jsi18n/ HTTP/1.1" 500 119796
INFO 2021-05-31 15:35:36,154 basehttp 154 "GET /xadmin/users/user/8/update/ HTTP/1.1" 200 30454
ERROR 2021-05-31 15:35:36,214 log 228 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 350, in i18n_javascript
    return JavaScriptCatalog.as_view(packages=['django.contrib.admin'])(request)
  File "E:\envs\luffy\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\i18n.py", line 201, in get
    self.translation = DjangoTranslation(locale, domain=domain, localedirs=paths)
  File "E:\envs\luffy\lib\site-packages\django\utils\translation\trans_real.py", line 151, in __init__
    translation = self._new_gnu_trans(localedir)
  File "E:\envs\luffy\lib\site-packages\django\utils\translation\trans_real.py", line 180, in _new_gnu_trans
    fallback=use_null_fallback,
  File "c:\python3.7\lib\gettext.py", line 533, in translation
    t = _translations.setdefault(key, class_(fp))
  File "c:\python3.7\lib\gettext.py", line 260, in __init__
    self._parse(fp)
  File "c:\python3.7\lib\gettext.py", line 353, in _parse
    magic = unpack('<I', buf[:4])[0]
struct.error: unpack requires a buffer of 4 bytes
ERROR 2021-05-31 15:35:36,215 basehttp 154 "GET /xadmin/jsi18n/ HTTP/1.1" 500 119805
INFO 2021-05-31 15:35:48,669 basehttp 154 "POST /xadmin/users/user/8/update/ HTTP/1.1" 302 0
INFO 2021-05-31 15:35:48,751 basehttp 154 "GET /xadmin/users/user/ HTTP/1.1" 200 41628
ERROR 2021-05-31 15:35:48,804 log 228 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 350, in i18n_javascript
    return JavaScriptCatalog.as_view(packages=['django.contrib.admin'])(request)
  File "E:\envs\luffy\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\i18n.py", line 201, in get
    self.translation = DjangoTranslation(locale, domain=domain, localedirs=paths)
  File "E:\envs\luffy\lib\site-packages\django\utils\translation\trans_real.py", line 151, in __init__
    translation = self._new_gnu_trans(localedir)
  File "E:\envs\luffy\lib\site-packages\django\utils\translation\trans_real.py", line 180, in _new_gnu_trans
    fallback=use_null_fallback,
  File "c:\python3.7\lib\gettext.py", line 533, in translation
    t = _translations.setdefault(key, class_(fp))
  File "c:\python3.7\lib\gettext.py", line 260, in __init__
    self._parse(fp)
  File "c:\python3.7\lib\gettext.py", line 353, in _parse
    magic = unpack('<I', buf[:4])[0]
struct.error: unpack requires a buffer of 4 bytes
ERROR 2021-05-31 15:35:48,806 basehttp 154 "GET /xadmin/jsi18n/ HTTP/1.1" 500 119796
INFO 2021-05-31 15:35:52,039 basehttp 154 "GET /xadmin/users/user/7/update/ HTTP/1.1" 200 30454
ERROR 2021-05-31 15:35:52,101 log 228 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 350, in i18n_javascript
    return JavaScriptCatalog.as_view(packages=['django.contrib.admin'])(request)
  File "E:\envs\luffy\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\i18n.py", line 201, in get
    self.translation = DjangoTranslation(locale, domain=domain, localedirs=paths)
  File "E:\envs\luffy\lib\site-packages\django\utils\translation\trans_real.py", line 151, in __init__
    translation = self._new_gnu_trans(localedir)
  File "E:\envs\luffy\lib\site-packages\django\utils\translation\trans_real.py", line 180, in _new_gnu_trans
    fallback=use_null_fallback,
  File "c:\python3.7\lib\gettext.py", line 533, in translation
    t = _translations.setdefault(key, class_(fp))
  File "c:\python3.7\lib\gettext.py", line 260, in __init__
    self._parse(fp)
  File "c:\python3.7\lib\gettext.py", line 353, in _parse
    magic = unpack('<I', buf[:4])[0]
struct.error: unpack requires a buffer of 4 bytes
ERROR 2021-05-31 15:35:52,102 basehttp 154 "GET /xadmin/jsi18n/ HTTP/1.1" 500 119805
INFO 2021-05-31 15:35:58,906 basehttp 154 "POST /xadmin/users/user/7/update/ HTTP/1.1" 302 0
INFO 2021-05-31 15:35:58,979 basehttp 154 "GET /xadmin/users/user/ HTTP/1.1" 200 41628
ERROR 2021-05-31 15:35:59,047 log 228 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\envs\luffy\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\xadmin\sites.py", line 350, in i18n_javascript
    return JavaScriptCatalog.as_view(packages=['django.contrib.admin'])(request)
  File "E:\envs\luffy\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\envs\luffy\lib\site-packages\django\views\i18n.py", line 201, in get
    self.translation = DjangoTranslation(locale, domain=domain, localedirs=paths)
  File "E:\envs\luffy\lib\site-packages\django\utils\translation\trans_real.py", line 151, in __init__
    translation = self._new_gnu_trans(localedir)
  File "E:\envs\luffy\lib\site-packages\django\utils\translation\trans_real.py", line 180, in _new_gnu_trans
    fallback=use_null_fallback,
  File "c:\python3.7\lib\gettext.py", line 533, in translation
    t = _translations.setdefault(key, class_(fp))
  File "c:\python3.7\lib\gettext.py", line 260, in __init__
    self._parse(fp)
  File "c:\python3.7\lib\gettext.py", line 353, in _parse
    magic = unpack('<I', buf[:4])[0]
struct.error: unpack requires a buffer of 4 bytes
ERROR 2021-05-31 15:35:59,049 basehttp 154 "GET /xadmin/jsi18n/ HTTP/1.1" 500 119796
INFO 2021-05-31 15:36:04,100 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-31 15:36:04,117 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-31 15:36:04,119 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
INFO 2021-05-31 15:36:18,782 basehttp 154 "GET /users/capycha/ HTTP/1.1" 200 105
INFO 2021-05-31 15:36:23,802 basehttp 154 "POST /users/capycha/ HTTP/1.1" 200 20
INFO 2021-05-31 15:36:23,906 basehttp 154 "POST /users/login/ HTTP/1.1" 200 188
INFO 2021-05-31 15:36:23,945 basehttp 154 "GET /home/banner/ HTTP/1.1" 200 291
INFO 2021-05-31 15:36:23,948 basehttp 154 "GET /home/nav/ HTTP/1.1" 200 430
INFO 2021-05-31 15:36:23,949 basehttp 154 "GET /home/btmnav/ HTTP/1.1" 200 192
WARNING 2021-05-31 15:36:32,344 log 228 Bad Request: /users/register/
WARNING 2021-05-31 15:36:32,344 basehttp 154 "POST /users/register/ HTTP/1.1" 400 131
INFO 2021-05-31 15:37:31,566 autoreload 597 Watching for file changes with StatReloader
